site_name: Flagsmith Docs. Feature Flags and Remote Config.

theme:
    name: material
    logo: 'images/logo.png'
    favicon: 'images/favicon.ico'
    icon:
        repo: fontawesome/brands/github
    custom_dir: overrides
    font:
        text: 'Source Sans Pro'
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections

site_url: https://docs.flagsmith.com/
repo_url: https://github.com/flagsmith/flagsmith-api
google_analytics: ['UA-120237963-2', 'flagsmith.com']
edit_uri: ''

markdown_extensions:
    - admonition
    - meta
    - pymdownx.highlight
    - pymdownx.superfences
    - attr_list

nav:
    - Flagsmith.com: 'https://www.flagsmith.com/'
    - Overview:
          - Overview: 'index.md'
          - Releases: 'releases.md'
          - Contributing: 'contributing.md'
    - Deployment:
          - Overview: 'deployment-overview.md'
          - Docker: 'docker.md'
          - Kubernetes: 'kubernetes.md'
          - OpenShift: 'openshift.md'
    - Dev Guide:
          - Overview: 'overview.md'
          - Fundamentals:
                - Managing Features: 'managing-features.md'
                - Managing Identities: 'managing-identities.md'
                - Managing Segments: 'managing-segments.md'
          - Advanced Use:
                - Staged Feature Rollouts: 'staged-feature-rollouts.md'
                - Flag Analytics: 'flag-analytics.md'
                - A/B Testing: 'ab-testing.md'
                - Integration Approaches: 'integration-approaches.md'
          - Administration:
                - API: 'api.md'
                - Web Hooks: 'system-administration.md'
                - Permissions: 'permissions.md'
                - Audit Logs: 'audit-logs.md'
    - SDKs:
          - REST: 'clients/rest.md'
          - Client Side:
                - Android: 'clients/android.md'
                - Flutter: 'clients/flutter.md'
                - iOS: 'clients/ios.md'
                - Javascript/React Native: 'clients/javascript.md'
          - Server Side:
                - Go: 'clients/go.md'
                - Java/Kotlin: 'clients/java.md'
                - Node: 'clients/node.md'
                - PHP: 'clients/php.md'
                - Python: 'clients/python.md'
                - Ruby: 'clients/ruby.md'
                - Rust: 'clients/rust.md'
                - .Net: 'clients/dotnet.md'
    - Integrations:
          - Overview: 'integrations/overview.md'
          - Analytics:
                - Amplitude: 'integrations/amplitude.md'
                - Heap Analytics: 'integrations/heap.md'
                - Mixpanel: 'integrations/mixpanel.md'
                - Segment: 'integrations/segment.md'
          - Infrastructure:
                - AppDynamics: 'integrations/appdynamics.md'
                - Datadog: 'integrations/datadog.md'
                - New Relic: 'integrations/newrelic.md'
                - Slack: 'integrations/slack.md'
    - Enterprise Edition:
          - Overview: 'enterprise/overview.md'
    - Log In: 'https://app.flagsmith.com/'
