site_name: Bullet Train Docs
theme: readthedocs
site_url: https://docs.bullet-train.io/
repo_url: https://github.com/SolidStateGroup/Bullet-Train-Docs
google_analytics: ['UA-120237963-2', 'bullet-train.io']

pages:
  - Overview and Install: index.md
  - Hosted Service: 'hosted-service.md'
  - Managing Features: 'managing-features.md'
  - Managing Identities: 'managing-identities.md'
  - Managing Segments: 'managing-segments.md'
  - Client Libraries: 
    - 'Javascript/React Native': 'clients/javascript.md'
    - 'Node': 'clients/node.md'
    - 'Java': 'clients/java.md'
    - 'Python': 'clients/python.md'
    - 'Ruby': 'clients/ruby.md'
    - '.Net': 'clients/dotnet.md'
    - 'REST': 'clients/rest.md'
