site_name: Bullet Train Docs

theme: 
  name: material
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'

site_url: https://docs.bullet-train.io/
repo_url: https://github.com/BulletTrainHQ/Bullet-Train-Docs
google_analytics: ['UA-120237963-2', 'bullet-train.io']

markdown_extensions:
  - admonition
  - meta

nav:
  - Overview and Install: index.md
  - Hosted Service: 'hosted-service.md'
  - Managing Features: 'managing-features.md'
  - Managing Identities: 'managing-identities.md'
  - Managing Segments: 'managing-segments.md'
  - Staged Feature Rollouts: 'staged-feature-rollouts.md'
  - A/B Testing: 'ab-testing.md'
  - Permissions: 'permissions.md'
  - System Administration: 'system-administration.md'
  - Audit Logs: 'audit-logs.md'
  - Client Libraries: 
    - 'Javascript/React Native': 'clients/javascript.md'
    - 'Node': 'clients/node.md'
    - 'Android': 'clients/android.md'
    - 'iOS': 'clients/ios.md'
    - 'Java': 'clients/java.md'
    - 'Python': 'clients/python.md'
    - 'Ruby': 'clients/ruby.md'
    - '.Net': 'clients/dotnet.md'
    - 'REST': 'clients/rest.md'
