site_name: Bullet Train Docs
theme: readthedocs
site_url: https://docs.bullet-train.io/
repo_url: https://github.com/SolidStateGroup/Bullet-Train-Docs

pages:
  - Overview: index.md
  - Installation: installation.md
  - Hosted Service: hosted-service.md
  - Clients: 
    - 'Overview' : 'clients/overview.md'
    - 'Javascript/React': 'clients/javascript.md'
    - 'Java': 'clients/java.md'
    - 'Node': 'clients/node.md'
