site_name: Flagsmith Docs

theme: 
  name: material
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  custom_dir: overrides
  font:
    text: 'Source Sans Pro'

site_url: https://docs.flagsmith.com/
repo_url: https://github.com/Flagsmith/flagsmith-docs
google_analytics: ['UA-120237963-2', 'flagsmith.com']

markdown_extensions:
  - admonition
  - meta
  - codehilite

extra_javascript:
  - javascripts/extra.js

nav:
  - Overview: 'index.md'
  - Releases:  'releases.md'
  - Hosted Service: 'hosted-service.md'
  - Using Flagsmith:
    - Overview: 'overview.md'
    - Managing Features: 'managing-features.md'
    - Managing Identities: 'managing-identities.md'
    - Managing Segments: 'managing-segments.md'
    - Staged Feature Rollouts: 'staged-feature-rollouts.md'
    - A/B Testing: 'ab-testing.md'
    - Integration Approaches: 'integration-approaches.md'
  - System Administration: 
    - Overview: 'system-administration.md'
    - Permissions: 'permissions.md'
    - API: 'api.md'
    - Audit Logs: 'audit-logs.md'
  - Integrations:
    - Amplitude: 'integrations/amplitude.md'
    - Datadog: 'integrations/datadog.md'
    - New Relic: 'integrations/newrelic.md'
    - Segment: 'integrations/segment.md'
    - Slack: 'integrations/slack.md'
  - SDK Client Libraries: 
    - Javascript/React Native: 'clients/javascript.md'
    - Node: 'clients/node.md'
    - Android: 'clients/android.md'
    - iOS: 'clients/ios.md'
    - Flutter: 'clients/flutter.md'
    - Java: 'clients/java.md'
    - Python: 'clients/python.md'
    - Ruby: 'clients/ruby.md'
    - .Net: 'clients/dotnet.md'
    - Go: 'clients/go.md'
    - Rust: 'clients/rust.md'
    - PHP: 'clients/php.md'
    - REST: 'clients/rest.md'
  - Open Source / Self Hosting:
    - Architecture:  'architecture.md'
    - Self Hosting:  'self-hosting.md'
    - Contributing:  'contributing.md'
  